logging:
  file: /var/log/tsf/${spring.application.name}/root.log
  level:
    root: INFO

server:
  port: 18081

management:
  server:
    port: 9876
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
  name: @project.name@
  version: @project.version@
  encoding: @project.build.sourceEncoding@
  java.version: @java.version@
